wget  https://eidoo.io/wp-content/uploads/tokens/eos.png -O  eos.png
wget  https://eidoo.io/wp-content/uploads/tokens/tron.png -O  trx.png
wget  https://eidoo.io/wp-content/uploads/tokens/binance-coin.png -O  bnb.png
wget  https://eidoo.io/wp-content/uploads/tokens/vechain.png -O  ven.png
wget  https://eidoo.io/wp-content/uploads/tokens/omisego.png -O  omg.png
wget  https://eidoo.io/wp-content/uploads/tokens/walton.png -O  wtc.png
wget  https://eidoo.io/wp-content/uploads/tokens/icon.png -O  icx.png
wget  https://eidoo.io/wp-content/uploads/tokens/zilliqa.png -O  zil.png
wget  https://eidoo.io/wp-content/uploads/tokens/aeternity.png -O  ae.png
wget  https://eidoo.io/wp-content/uploads/tokens/0x.png -O  zrx.png
wget  https://eidoo.io/wp-content/uploads/tokens/bytom.png -O  btm.png
wget  https://eidoo.io/wp-content/uploads/tokens/augur.png -O  rep.png
wget  https://eidoo.io/wp-content/uploads/tokens/maker.png -O  mkr.png
wget  https://eidoo.io/wp-content/uploads/tokens/populous.png -O  ppt.png
wget  https://eidoo.io/wp-content/uploads/tokens/golem-network-tokens.png -O  gnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/rchain.png -O  rhoc.png
wget  https://eidoo.io/wp-content/uploads/tokens/status.png -O  snt.png
wget  https://eidoo.io/wp-content/uploads/tokens/iostoken.png -O  iost.png
wget  https://eidoo.io/wp-content/uploads/tokens/mixin.png -O  xin.png
wget  https://eidoo.io/wp-content/uploads/tokens/nebulas-token.png -O  nas.png
wget  https://eidoo.io/wp-content/uploads/tokens/kucoin-shares.png -O  kcs.png
wget  https://eidoo.io/wp-content/uploads/tokens/waltonchain.png -O  wtc.png
wget  https://eidoo.io/wp-content/uploads/tokens/loopring.png -O  lrc.png
wget  https://eidoo.io/wp-content/uploads/tokens/digixdao.png -O  dgd.png
wget  https://eidoo.io/wp-content/uploads/tokens/aelf.png -O  elf.png
wget  https://eidoo.io/wp-content/uploads/tokens/aion.png -O  aion.png
wget  https://eidoo.io/wp-content/uploads/tokens/bancor.png -O  bnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/xplay.png -O  xpa.png
wget  https://eidoo.io/wp-content/uploads/tokens/funfair.png -O  fun.png
wget  https://eidoo.io/wp-content/uploads/tokens/cybermiles.png -O  cmt.png
wget  https://eidoo.io/wp-content/uploads/tokens/kyber-network.png -O  knc.png
wget  https://eidoo.io/wp-content/uploads/tokens/dentacoin.png -O  dcn.png
wget  https://eidoo.io/wp-content/uploads/tokens/monaco.png -O  mco.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethos.png -O  ethos.png
wget  https://eidoo.io/wp-content/uploads/tokens/enigma-project.png -O  eng.png
wget  https://eidoo.io/wp-content/uploads/tokens/veritaseum.png -O  veri.png
wget  https://eidoo.io/wp-content/uploads/tokens/decentraland.png -O  mana.png
wget  https://eidoo.io/wp-content/uploads/tokens/kin.png -O  kin.png
wget  https://eidoo.io/wp-content/uploads/tokens/wax.png -O  wax.png
wget  https://eidoo.io/wp-content/uploads/tokens/theta-token.png -O  theta.png
wget  https://eidoo.io/wp-content/uploads/tokens/power-ledger.png -O  powr.png
wget  https://eidoo.io/wp-content/uploads/tokens/oyster-pearl.png -O  prl.png
wget  https://eidoo.io/wp-content/uploads/tokens/moac.png -O  moac.png
wget  https://eidoo.io/wp-content/uploads/tokens/polymath-network.png -O  poly.png
wget  https://eidoo.io/wp-content/uploads/tokens/qash.png -O  qash.png
wget  https://eidoo.io/wp-content/uploads/tokens/nuls.png -O  nuls.png
wget  https://eidoo.io/wp-content/uploads/tokens/bibox-token.png -O  bix.png
wget  https://eidoo.io/wp-content/uploads/tokens/paypex.png -O  payx.png
wget  https://eidoo.io/wp-content/uploads/tokens/scryinfo.png -O  ddd.png
wget  https://eidoo.io/wp-content/uploads/tokens/gifto.png -O  gto.png
wget  https://eidoo.io/wp-content/uploads/tokens/game.png -O  gtc.png
wget  https://eidoo.io/wp-content/uploads/tokens/storm.png -O  storm.png
wget  https://eidoo.io/wp-content/uploads/tokens/substratum.png -O  sub.png
wget  https://eidoo.io/wp-content/uploads/tokens/chainlink.png -O  link.png
wget  https://eidoo.io/wp-content/uploads/tokens/fusion.png -O  fsn.png
wget  https://eidoo.io/wp-content/uploads/tokens/tenx.png -O  pay.png
wget  https://eidoo.io/wp-content/uploads/tokens/salt.png -O  salt.png
wget  https://eidoo.io/wp-content/uploads/tokens/storj.png -O  storj.png
wget  https://eidoo.io/wp-content/uploads/tokens/dragonchain.png -O  drgn.png
wget  https://eidoo.io/wp-content/uploads/tokens/revain.png -O  r.png
wget  https://eidoo.io/wp-content/uploads/tokens/medishares.png -O  mds.png
wget  https://eidoo.io/wp-content/uploads/tokens/civic.png -O  cvc.png
wget  https://eidoo.io/wp-content/uploads/tokens/iconomi.png -O  icn.png
wget  https://eidoo.io/wp-content/uploads/tokens/bluzelle.png -O  blz.png
wget  https://eidoo.io/wp-content/uploads/tokens/singularitynet.png -O  agi.png
wget  https://eidoo.io/wp-content/uploads/tokens/time-new-bank.png -O  tnb.png
wget  https://eidoo.io/wp-content/uploads/tokens/rlc.png -O  rlc.png
wget  https://eidoo.io/wp-content/uploads/tokens/nucleus-vision.png -O  ncash.png
wget  https://eidoo.io/wp-content/uploads/tokens/selfkey.png -O  key.png
wget  https://eidoo.io/wp-content/uploads/tokens/sonm.png -O  snm.png
wget  https://eidoo.io/wp-content/uploads/tokens/ruff.png -O  ruff.png
wget  https://eidoo.io/wp-content/uploads/tokens/request-network.png -O  req.png
wget  https://eidoo.io/wp-content/uploads/tokens/hive.png -O  hvn.png
wget  https://eidoo.io/wp-content/uploads/tokens/smartmesh.png -O  smt.png
wget  https://eidoo.io/wp-content/uploads/tokens/aragon.png -O  ant.png
wget  https://eidoo.io/wp-content/uploads/tokens/dew.png -O  dew.png
wget  https://eidoo.io/wp-content/uploads/tokens/streamr-datacoin.png -O  data.png
wget  https://eidoo.io/wp-content/uploads/tokens/arcblock.png -O  abt.png
wget  https://eidoo.io/wp-content/uploads/tokens/gnosis-gno.png -O  gno.png
wget  https://eidoo.io/wp-content/uploads/tokens/dai.png -O  dai.png
wget  https://eidoo.io/wp-content/uploads/tokens/cindicator.png -O  cnd.png
wget  https://eidoo.io/wp-content/uploads/tokens/bottos.png -O  bto.png
wget  https://eidoo.io/wp-content/uploads/tokens/poet.png -O  poe.png
wget  https://eidoo.io/wp-content/uploads/tokens/all-sports.png -O  soc.png
wget  https://eidoo.io/wp-content/uploads/tokens/quantstamp.png -O  qsp.png
wget  https://eidoo.io/wp-content/uploads/tokens/educare.png -O  ekt.png
wget  https://eidoo.io/wp-content/uploads/tokens/blockv.png -O  vee.png
wget  https://eidoo.io/wp-content/uploads/tokens/enjin-coin.png -O  enj.png
wget  https://eidoo.io/wp-content/uploads/tokens/amber.png -O  amb.png
wget  https://eidoo.io/wp-content/uploads/tokens/credits.png -O  cs.png
wget  https://eidoo.io/wp-content/uploads/tokens/sophiatx.png -O  sphtx.png
wget  https://eidoo.io/wp-content/uploads/tokens/bread.png -O  brd.png
wget  https://eidoo.io/wp-content/uploads/tokens/genaro-network.png -O  gnx.png
wget  https://eidoo.io/wp-content/uploads/tokens/c20.png -O  c20.png
wget  https://eidoo.io/wp-content/uploads/tokens/sirin-labs-token.png -O  srn.png
wget  https://eidoo.io/wp-content/uploads/tokens/cube.png -O  auto.png
wget  https://eidoo.io/wp-content/uploads/tokens/dent.png -O  dent.png
wget  https://eidoo.io/wp-content/uploads/tokens/odyssey.png -O  ocn.png
wget  https://eidoo.io/wp-content/uploads/tokens/coindash.png -O  cdt.png
wget  https://eidoo.io/wp-content/uploads/tokens/simple-token.png -O  ost.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethlend.png -O  lend.png
wget  https://eidoo.io/wp-content/uploads/tokens/crypterium.png -O  crpt.png
wget  https://eidoo.io/wp-content/uploads/tokens/pillar.png -O  plr.png
wget  https://eidoo.io/wp-content/uploads/tokens/iot-chain.png -O  itc.png
wget  https://eidoo.io/wp-content/uploads/tokens/data.png -O  dta.png
wget  https://eidoo.io/wp-content/uploads/tokens/metal.png -O  mtl.png
wget  https://eidoo.io/wp-content/uploads/tokens/telcoin.png -O  tel.png
wget  https://eidoo.io/wp-content/uploads/tokens/trade-token.png -O  tio.png
wget  https://eidoo.io/wp-content/uploads/tokens/genesis-vision.png -O  gvt.png
wget  https://eidoo.io/wp-content/uploads/tokens/edgeless.png -O  edg.png
wget  https://eidoo.io/wp-content/uploads/tokens/rock.png -O  rkt.png
wget  https://eidoo.io/wp-content/uploads/tokens/adx-net.png -O  adx.png
wget  https://eidoo.io/wp-content/uploads/tokens/origintrail.png -O  trac.png
wget  https://eidoo.io/wp-content/uploads/tokens/eidoo.png -O  edo.png
wget  https://eidoo.io/wp-content/uploads/tokens/jibrel-network.png -O  jnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/lympo.png -O  lym.png
wget  https://eidoo.io/wp-content/uploads/tokens/tokencard.png -O  tkn.png
wget  https://eidoo.io/wp-content/uploads/tokens/bcap.png -O  bcap.png
wget  https://eidoo.io/wp-content/uploads/tokens/singulardtv.png -O  sngls.png
wget  https://eidoo.io/wp-content/uploads/tokens/swftcoin.png -O  swftc.png
wget  https://eidoo.io/wp-content/uploads/tokens/delphy.png -O  dpy.png
wget  https://eidoo.io/wp-content/uploads/tokens/spankchain.png -O  spank.png
wget  https://eidoo.io/wp-content/uploads/tokens/universa.png -O  utnp.png
wget  https://eidoo.io/wp-content/uploads/tokens/paypie.png -O  ppp.png
wget  https://eidoo.io/wp-content/uploads/tokens/yee.png -O  yee.png
wget  https://eidoo.io/wp-content/uploads/tokens/district0x.png -O  dnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/tokenclub.png -O  tct.png
wget  https://eidoo.io/wp-content/uploads/tokens/appcoins.png -O  appc.png
wget  https://eidoo.io/wp-content/uploads/tokens/presearch.png -O  pre.png
wget  https://eidoo.io/wp-content/uploads/tokens/airswap.png -O  ast.png
wget  https://eidoo.io/wp-content/uploads/tokens/utrust.png -O  utk.png
wget  https://eidoo.io/wp-content/uploads/tokens/kickico.png -O  kick.png
wget  https://eidoo.io/wp-content/uploads/tokens/wings.png -O  wings.png
wget  https://eidoo.io/wp-content/uploads/tokens/wepower.png -O  wpr.png
wget  https://eidoo.io/wp-content/uploads/tokens/cpchain.png -O  cpc.png
wget  https://eidoo.io/wp-content/uploads/tokens/tierion.png -O  tnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/swarm-fund.png -O  swm.png
wget  https://eidoo.io/wp-content/uploads/tokens/ins-ecosystem.png -O  ins.png
wget  https://eidoo.io/wp-content/uploads/tokens/modum.png -O  mod.png
wget  https://eidoo.io/wp-content/uploads/tokens/hydro-protocol.png -O  hot.png
wget  https://eidoo.io/wp-content/uploads/tokens/mobilego.png -O  mgo.png
wget  https://eidoo.io/wp-content/uploads/tokens/etherparty.png -O  fuel.png
wget  https://eidoo.io/wp-content/uploads/tokens/wabi.png -O  wabi.png
wget  https://eidoo.io/wp-content/uploads/tokens/ugchain.png -O  ugc.png
wget  https://eidoo.io/wp-content/uploads/tokens/melon.png -O  mln.png
wget  https://eidoo.io/wp-content/uploads/tokens/lunyr.png -O  lun.png
wget  https://eidoo.io/wp-content/uploads/tokens/atn.png -O  atn.png
wget  https://eidoo.io/wp-content/uploads/tokens/blox.png -O  cdt.png
wget  https://eidoo.io/wp-content/uploads/tokens/naga.png -O  ngc.png
wget  https://eidoo.io/wp-content/uploads/tokens/taas.png -O  taas.png
wget  https://eidoo.io/wp-content/uploads/tokens/decent-bet.png -O  dbet.png
wget  https://eidoo.io/wp-content/uploads/tokens/credo.png -O  credo.png
wget  https://eidoo.io/wp-content/uploads/tokens/mothership.png -O  msp.png
wget  https://eidoo.io/wp-content/uploads/tokens/selfsell.png -O  ssc.png
wget  https://eidoo.io/wp-content/uploads/tokens/datum.png -O  dat.png
wget  https://eidoo.io/wp-content/uploads/tokens/primas.png -O  pst.png
wget  https://eidoo.io/wp-content/uploads/tokens/vibe.png -O  vibe.png
wget  https://eidoo.io/wp-content/uploads/tokens/decision-token.png -O  hst.png
wget  https://eidoo.io/wp-content/uploads/tokens/humaniq.png -O  hmq.png
wget  https://eidoo.io/wp-content/uploads/tokens/hive-project.png -O  hvn.png
wget  https://eidoo.io/wp-content/uploads/tokens/aurora-dao.png -O  aura.png
wget  https://eidoo.io/wp-content/uploads/tokens/oneroot-network.png -O  rnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/sportyfi.png -O  spf.png
wget  https://eidoo.io/wp-content/uploads/tokens/cashaa.png -O  cas.png
wget  https://eidoo.io/wp-content/uploads/tokens/oyster.png -O  prl.png
wget  https://eidoo.io/wp-content/uploads/tokens/bankex.png -O  bkx.png
wget  https://eidoo.io/wp-content/uploads/tokens/envion.png -O  evn.png
wget  https://eidoo.io/wp-content/uploads/tokens/qunqun.png -O  qun.png
wget  https://eidoo.io/wp-content/uploads/tokens/firstblood.png -O  1st.png
wget  https://eidoo.io/wp-content/uploads/tokens/zeusshield.png -O  zsc.png
wget  https://eidoo.io/wp-content/uploads/tokens/fortuna.png -O  fota.png
wget  https://eidoo.io/wp-content/uploads/tokens/coss.png -O  coss.png
wget  https://eidoo.io/wp-content/uploads/tokens/cofound-it.png -O  cfi.png
wget  https://eidoo.io/wp-content/uploads/tokens/soarcoin.png -O  soar.png
wget  https://eidoo.io/wp-content/uploads/tokens/blackmoon.png -O  bmc.png
wget  https://eidoo.io/wp-content/uploads/tokens/prochain.png -O  pro.png
wget  https://eidoo.io/wp-content/uploads/tokens/aichain.png -O  ait.png
wget  https://eidoo.io/wp-content/uploads/tokens/viberate.png -O  vib.png
wget  https://eidoo.io/wp-content/uploads/tokens/everex.png -O  evx.png
wget  https://eidoo.io/wp-content/uploads/tokens/covesting.png -O  cov.png
wget  https://eidoo.io/wp-content/uploads/tokens/datawallet.png -O  dxt.png
wget  https://eidoo.io/wp-content/uploads/tokens/ixledger.png -O  ixt.png
wget  https://eidoo.io/wp-content/uploads/tokens/maecenas.png -O  art.png
wget  https://eidoo.io/wp-content/uploads/tokens/ormeus-coin.png -O  orme.png
wget  https://eidoo.io/wp-content/uploads/tokens/propy.png -O  pro.png
wget  https://eidoo.io/wp-content/uploads/tokens/medical-chain.png -O  mtn.png
wget  https://eidoo.io/wp-content/uploads/tokens/true-usd.png -O  tusd.png
wget  https://eidoo.io/wp-content/uploads/tokens/stk.png -O  stk.png
wget  https://eidoo.io/wp-content/uploads/tokens/unikoin-gold.png -O  ukg.png
wget  https://eidoo.io/wp-content/uploads/tokens/quantum.png -O  qau.png
wget  https://eidoo.io/wp-content/uploads/tokens/grid.png -O  grid.png
wget  https://eidoo.io/wp-content/uploads/tokens/life.png -O  life.png
wget  https://eidoo.io/wp-content/uploads/tokens/polybius.png -O  plbt.png
wget  https://eidoo.io/wp-content/uploads/tokens/ties-network.png -O  tie.png
wget  https://eidoo.io/wp-content/uploads/tokens/cobinhood.png -O  cob.png
wget  https://eidoo.io/wp-content/uploads/tokens/rialto.png -O  xrl.png
wget  https://eidoo.io/wp-content/uploads/tokens/bloomtoken.png -O  blt.png
wget  https://eidoo.io/wp-content/uploads/tokens/olympus-labs.png -O  mot.png
wget  https://eidoo.io/wp-content/uploads/tokens/lamden.png -O  tau.png
wget  https://eidoo.io/wp-content/uploads/tokens/neurotoken.png -O  ntk.png
wget  https://eidoo.io/wp-content/uploads/tokens/suncontract.png -O  snc.png
wget  https://eidoo.io/wp-content/uploads/tokens/adtoken.png -O  adt.png
wget  https://eidoo.io/wp-content/uploads/tokens/latoken.png -O  la.png
wget  https://eidoo.io/wp-content/uploads/tokens/energo.png -O  tsl.png
wget  https://eidoo.io/wp-content/uploads/tokens/nework.png -O  nkc.png
wget  https://eidoo.io/wp-content/uploads/tokens/gems-protocol.png -O  gem.png
wget  https://eidoo.io/wp-content/uploads/tokens/refereum.png -O  rfr.png
wget  https://eidoo.io/wp-content/uploads/tokens/dadi.png -O  dadi.png
wget  https://eidoo.io/wp-content/uploads/tokens/neumark.png -O  neu.png
wget  https://eidoo.io/wp-content/uploads/tokens/guppy.png -O  gup.png
wget  https://eidoo.io/wp-content/uploads/tokens/blockport.png -O  bpt.png
wget  https://eidoo.io/wp-content/uploads/tokens/numeraire.png -O  nmr.png
wget  https://eidoo.io/wp-content/uploads/tokens/aeron.png -O  arn.png
wget  https://eidoo.io/wp-content/uploads/tokens/blocktix.png -O  tix.png
wget  https://eidoo.io/wp-content/uploads/tokens/chronobank.png -O  time.png
wget  https://eidoo.io/wp-content/uploads/tokens/uquid-coin.png -O  uqc.png
wget  https://eidoo.io/wp-content/uploads/tokens/oax.png -O  oax.png
wget  https://eidoo.io/wp-content/uploads/tokens/monetha.png -O  mth.png
wget  https://eidoo.io/wp-content/uploads/tokens/divi.png -O  divx.png
wget  https://eidoo.io/wp-content/uploads/tokens/aidoc.png -O  aidoc.png
wget  https://eidoo.io/wp-content/uploads/tokens/dmarket.png -O  dmt.png
wget  https://eidoo.io/wp-content/uploads/tokens/agrello-delta.png -O  dlt.png
wget  https://eidoo.io/wp-content/uploads/tokens/everus.png -O  evr.png
wget  https://eidoo.io/wp-content/uploads/tokens/etheroll.png -O  dice.png
wget  https://eidoo.io/wp-content/uploads/tokens/stox.png -O  stx.png
wget  https://eidoo.io/wp-content/uploads/tokens/carvertical.png -O  cv.png
wget  https://eidoo.io/wp-content/uploads/tokens/remme.png -O  rem.png
wget  https://eidoo.io/wp-content/uploads/tokens/social.png -O  scl.png
wget  https://eidoo.io/wp-content/uploads/tokens/swissborg.png -O  chsb.png
wget  https://eidoo.io/wp-content/uploads/tokens/hacken.png -O  hkn.png
wget  https://eidoo.io/wp-content/uploads/tokens/cappasity.png -O  capp.png
wget  https://eidoo.io/wp-content/uploads/tokens/attention-token-of-media.png -O  atm.png
wget  https://eidoo.io/wp-content/uploads/tokens/lockchain.png -O  loc.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitclave.png -O  cat.png
wget  https://eidoo.io/wp-content/uploads/tokens/echolink.png -O  eko.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitqy.png -O  bq.png
wget  https://eidoo.io/wp-content/uploads/tokens/icos.png -O  icos.png
wget  https://eidoo.io/wp-content/uploads/tokens/paragon.png -O  prg.png
wget  https://eidoo.io/wp-content/uploads/tokens/axpire.png -O  axp.png
wget  https://eidoo.io/wp-content/uploads/tokens/dovu.png -O  dovu.png
wget  https://eidoo.io/wp-content/uploads/tokens/arcade-token.png -O  arc.png
wget  https://eidoo.io/wp-content/uploads/tokens/exrnchain.png -O  exrn.png
wget  https://eidoo.io/wp-content/uploads/tokens/leverj.png -O  lev.png
wget  https://eidoo.io/wp-content/uploads/tokens/elixir.png -O  elix.png
wget  https://eidoo.io/wp-content/uploads/tokens/investfeed.png -O  ift.png
wget  https://eidoo.io/wp-content/uploads/tokens/xaurum.png -O  xaur.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitdegree.png -O  bdg.png
wget  https://eidoo.io/wp-content/uploads/tokens/matryx.png -O  mtx.png
wget  https://eidoo.io/wp-content/uploads/tokens/domraider.png -O  drt.png
wget  https://eidoo.io/wp-content/uploads/tokens/rivetz.png -O  rvt.png
wget  https://eidoo.io/wp-content/uploads/tokens/airtoken.png -O  air.png
wget  https://eidoo.io/wp-content/uploads/tokens/indahash.png -O  idh.png
wget  https://eidoo.io/wp-content/uploads/tokens/insurepal.png -O  ipl.png
wget  https://eidoo.io/wp-content/uploads/tokens/flixxo.png -O  flixx.png
wget  https://eidoo.io/wp-content/uploads/tokens/smartbillions.png -O  smart.png
wget  https://eidoo.io/wp-content/uploads/tokens/swarm-city.png -O  swt.png
wget  https://eidoo.io/wp-content/uploads/tokens/nexium.png -O  nxc.png
wget  https://eidoo.io/wp-content/uploads/tokens/get-protocol.png -O  get.png
wget  https://eidoo.io/wp-content/uploads/tokens/aventus.png -O  avt.png
wget  https://eidoo.io/wp-content/uploads/tokens/ucash.png -O  ucash.png
wget  https://eidoo.io/wp-content/uploads/tokens/bezop.png -O  bez.png
wget  https://eidoo.io/wp-content/uploads/tokens/change.png -O  cag.png
wget  https://eidoo.io/wp-content/uploads/tokens/sharex.png -O  sexc.png
wget  https://eidoo.io/wp-content/uploads/tokens/eroscoin.png -O  ero.png
wget  https://eidoo.io/wp-content/uploads/tokens/playkey.png -O  pkt.png
wget  https://eidoo.io/wp-content/uploads/tokens/hubii-network.png -O  hbt.png
wget  https://eidoo.io/wp-content/uploads/tokens/zap.png -O  zap.png
wget  https://eidoo.io/wp-content/uploads/tokens/cargox.png -O  cxo.png
wget  https://eidoo.io/wp-content/uploads/tokens/patientory.png -O  ptoy.png
wget  https://eidoo.io/wp-content/uploads/tokens/bee-token.png -O  bee.png
wget  https://eidoo.io/wp-content/uploads/tokens/encrypgen.png -O  dna.png
wget  https://eidoo.io/wp-content/uploads/tokens/b2bx.png -O  b2b.png
wget  https://eidoo.io/wp-content/uploads/tokens/canyacoin.png -O  can.png
wget  https://eidoo.io/wp-content/uploads/tokens/zilla.png -O  zla.png
wget  https://eidoo.io/wp-content/uploads/tokens/idex-membership.png -O  idxm.png
wget  https://eidoo.io/wp-content/uploads/tokens/target-coin.png -O  tgt.png
wget  https://eidoo.io/wp-content/uploads/tokens/trust.png -O  trst.png
wget  https://eidoo.io/wp-content/uploads/tokens/aidcoin.png -O  aid.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitdice.png -O  csno.png
wget  https://eidoo.io/wp-content/uploads/tokens/ink-protocol.png -O  xnk.png
wget  https://eidoo.io/wp-content/uploads/tokens/xpa.png -O  xpa.png
wget  https://eidoo.io/wp-content/uploads/tokens/bounty0x.png -O  bnty.png
wget  https://eidoo.io/wp-content/uploads/tokens/real-estate-tokens.png -O  rex.png
wget  https://eidoo.io/wp-content/uploads/tokens/adbank.png -O  adb.png
wget  https://eidoo.io/wp-content/uploads/tokens/prospectors-gold.png -O  pgl.png
wget  https://eidoo.io/wp-content/uploads/tokens/hedge.png -O  hdg.png
wget  https://eidoo.io/wp-content/uploads/tokens/mysterium.png -O  myst.png
wget  https://eidoo.io/wp-content/uploads/tokens/astro.png -O  astro.png
wget  https://eidoo.io/wp-content/uploads/tokens/nimiq.png -O  net.png
wget  https://eidoo.io/wp-content/uploads/tokens/clearpoll.png -O  poll.png
wget  https://eidoo.io/wp-content/uploads/tokens/snovio.png -O  snov.png
wget  https://eidoo.io/wp-content/uploads/tokens/sharechain.png -O  sss.png
wget  https://eidoo.io/wp-content/uploads/tokens/trueflip.png -O  tfl.png
wget  https://eidoo.io/wp-content/uploads/tokens/mybit-token.png -O  myb.png
wget  https://eidoo.io/wp-content/uploads/tokens/coinfi.png -O  cofi.png
wget  https://eidoo.io/wp-content/uploads/tokens/pluton.png -O  plu.png
wget  https://eidoo.io/wp-content/uploads/tokens/privatix.png -O  prix.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethereum-blue.png -O  blue.png
wget  https://eidoo.io/wp-content/uploads/tokens/alis.png -O  alis.png
wget  https://eidoo.io/wp-content/uploads/tokens/sense.png -O  sense.png
wget  https://eidoo.io/wp-content/uploads/tokens/worldcore.png -O  wrc.png
wget  https://eidoo.io/wp-content/uploads/tokens/devery.png -O  eve.png
wget  https://eidoo.io/wp-content/uploads/tokens/block-array.png -O  ary.png
wget  https://eidoo.io/wp-content/uploads/tokens/adshares.png -O  adst.png
wget  https://eidoo.io/wp-content/uploads/tokens/sether.png -O  seth.png
wget  https://eidoo.io/wp-content/uploads/tokens/gladius-token.png -O  gla.png
wget  https://eidoo.io/wp-content/uploads/tokens/eztoken.png -O  ezt.png
wget  https://eidoo.io/wp-content/uploads/tokens/dao-casino.png -O  bet.png
wget  https://eidoo.io/wp-content/uploads/tokens/cryptopay.png -O  cpay.png
wget  https://eidoo.io/wp-content/uploads/tokens/real.png -O  real.png
wget  https://eidoo.io/wp-content/uploads/tokens/vslice.png -O  vsl.png
wget  https://eidoo.io/wp-content/uploads/tokens/internxt.png -O  inxt.png
wget  https://eidoo.io/wp-content/uploads/tokens/vezt.png -O  vzt.png
wget  https://eidoo.io/wp-content/uploads/tokens/gatcoin.png -O  gat.png
wget  https://eidoo.io/wp-content/uploads/tokens/fidentiax.png -O  fdx.png
wget  https://eidoo.io/wp-content/uploads/tokens/atlant.png -O  atl.png
wget  https://eidoo.io/wp-content/uploads/tokens/payfair.png -O  pfr.png
wget  https://eidoo.io/wp-content/uploads/tokens/gimli.png -O  gim.png
wget  https://eidoo.io/wp-content/uploads/tokens/sportyco.png -O  spf.png
wget  https://eidoo.io/wp-content/uploads/tokens/dether.png -O  dth.png
wget  https://eidoo.io/wp-content/uploads/tokens/indorse-token.png -O  ind.png
wget  https://eidoo.io/wp-content/uploads/tokens/experty.png -O  exy.png
wget  https://eidoo.io/wp-content/uploads/tokens/voisecom.png -O  voise.png
wget  https://eidoo.io/wp-content/uploads/tokens/iungo.png -O  ing.png
wget  https://eidoo.io/wp-content/uploads/tokens/hellogold.png -O  hgt.png
wget  https://eidoo.io/wp-content/uploads/tokens/herocoin.png -O  play.png
wget  https://eidoo.io/wp-content/uploads/tokens/sociall.png -O  scl.png
wget  https://eidoo.io/wp-content/uploads/tokens/triaconta.png -O  tria.png
wget  https://eidoo.io/wp-content/uploads/tokens/giga-watt-token.png -O  wtt.png
wget  https://eidoo.io/wp-content/uploads/tokens/starbase.png -O  star.png
wget  https://eidoo.io/wp-content/uploads/tokens/goodomy.png -O  good.png
wget  https://eidoo.io/wp-content/uploads/tokens/blockcat.png -O  cat.png
wget  https://eidoo.io/wp-content/uploads/tokens/upfiring.png -O  ufr.png
wget  https://eidoo.io/wp-content/uploads/tokens/bonpay.png -O  bon.png
wget  https://eidoo.io/wp-content/uploads/tokens/publica.png -O  pbl.png
wget  https://eidoo.io/wp-content/uploads/tokens/mywish.png -O  wish.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitboost.png -O  bbt.png
wget  https://eidoo.io/wp-content/uploads/tokens/flypme.png -O  fyp.png
wget  https://eidoo.io/wp-content/uploads/tokens/opus.png -O  opt.png
wget  https://eidoo.io/wp-content/uploads/tokens/copytrack.png -O  cpy.png
wget  https://eidoo.io/wp-content/uploads/tokens/maverick-chain.png -O  mvc.png
wget  https://eidoo.io/wp-content/uploads/tokens/xenon.png -O  xnn.png
wget  https://eidoo.io/wp-content/uploads/tokens/tiesdb.png -O  tie.png
wget  https://eidoo.io/wp-content/uploads/tokens/aigang.png -O  aix.png
wget  https://eidoo.io/wp-content/uploads/tokens/coinlancer.png -O  cl.png
wget  https://eidoo.io/wp-content/uploads/tokens/dcorp.png -O  drp.png
wget  https://eidoo.io/wp-content/uploads/tokens/digipulse.png -O  dgpt.png
wget  https://eidoo.io/wp-content/uploads/tokens/lampix.png -O  pix.png
wget  https://eidoo.io/wp-content/uploads/tokens/viuly.png -O  viu.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethbits.png -O  etbs.png
wget  https://eidoo.io/wp-content/uploads/tokens/sugar-exchange.png -O  sgr.png
wget  https://eidoo.io/wp-content/uploads/tokens/reftoken.png -O  ref.png
wget  https://eidoo.io/wp-content/uploads/tokens/ongsocial.png -O  ong.png
wget  https://eidoo.io/wp-content/uploads/tokens/mercury-protocol.png -O  gmt.png
wget  https://eidoo.io/wp-content/uploads/tokens/autonio.png -O  nio.png
wget  https://eidoo.io/wp-content/uploads/tokens/tokenbox.png -O  tbx.png
wget  https://eidoo.io/wp-content/uploads/tokens/locicoin.png -O  loci.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethorse.png -O  horse.png
wget  https://eidoo.io/wp-content/uploads/tokens/eventchain.png -O  evc.png
wget  https://eidoo.io/wp-content/uploads/tokens/verify.png -O  cred.png
wget  https://eidoo.io/wp-content/uploads/tokens/micromoney.png -O  amm.png
wget  https://eidoo.io/wp-content/uploads/tokens/ebtcnew.png -O  ebtc.png
wget  https://eidoo.io/wp-content/uploads/tokens/pylon-network.png -O  pylnt.png
wget  https://eidoo.io/wp-content/uploads/tokens/centra.png -O  ctr.png
wget  https://eidoo.io/wp-content/uploads/tokens/skincoin.png -O  skin.png
wget  https://eidoo.io/wp-content/uploads/tokens/ace.png -O  ace.png
wget  https://eidoo.io/wp-content/uploads/tokens/tracto.png -O  trct.png
wget  https://eidoo.io/wp-content/uploads/tokens/fucktoken.png -O  fuck.png
wget  https://eidoo.io/wp-content/uploads/tokens/neverdie.png -O  ndc.png
wget  https://eidoo.io/wp-content/uploads/tokens/creditbit.png -O  crb.png
wget  https://eidoo.io/wp-content/uploads/tokens/farad.png -O  frd.png
wget  https://eidoo.io/wp-content/uploads/tokens/legends-room.png -O  lgd.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethersportz.png -O  esz.png
wget  https://eidoo.io/wp-content/uploads/tokens/ebitcoin-cash.png -O  ebch.png
wget  https://eidoo.io/wp-content/uploads/tokens/wandx.png -O  wand.png
wget  https://eidoo.io/wp-content/uploads/tokens/etheriya.png -O  riya.png
wget  https://eidoo.io/wp-content/uploads/tokens/chronologic.png -O  day.png
wget  https://eidoo.io/wp-content/uploads/tokens/student-coin.png -O  stu.png
wget  https://eidoo.io/wp-content/uploads/tokens/embers.png -O  mbrs.png
wget  https://eidoo.io/wp-content/uploads/tokens/emphy.png -O  epy.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitpark-coin.png -O  bpc.png
wget  https://eidoo.io/wp-content/uploads/tokens/global-jobcoin.png -O  gjc.png
wget  https://eidoo.io/wp-content/uploads/tokens/musiconomi.png -O  mci.png
wget  https://eidoo.io/wp-content/uploads/tokens/authorship.png -O  ats.png
wget  https://eidoo.io/wp-content/uploads/tokens/roulettetoken.png -O  rlt.png
wget  https://eidoo.io/wp-content/uploads/tokens/suretly.png -O  sur.png
wget  https://eidoo.io/wp-content/uploads/tokens/starcredits.png -O  strc.png
wget  https://eidoo.io/wp-content/uploads/tokens/soma.png -O  sct.png
wget  https://eidoo.io/wp-content/uploads/tokens/hawla-today.png -O  hat.png
wget  https://eidoo.io/wp-content/uploads/tokens/equal.png -O  eql.png
wget  https://eidoo.io/wp-content/uploads/tokens/nitro.png -O  nox.png
wget  https://eidoo.io/wp-content/uploads/tokens/drp-utility.png -O  drpu.png
wget  https://eidoo.io/wp-content/uploads/tokens/fundyourselfnow.png -O  fyn.png
wget  https://eidoo.io/wp-content/uploads/tokens/tigereum.png -O  tig.png
wget  https://eidoo.io/wp-content/uploads/tokens/qvolta.png -O  qvt.png
wget  https://eidoo.io/wp-content/uploads/tokens/mcap.png -O  mcap.png
wget  https://eidoo.io/wp-content/uploads/tokens/flik.png -O  flik.png
wget  https://eidoo.io/wp-content/uploads/tokens/piplcoin.png -O  pipl.png
wget  https://eidoo.io/wp-content/uploads/tokens/jetcoin.png -O  jet.png
wget  https://eidoo.io/wp-content/uploads/tokens/wild-crypto.png -O  wild.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethbet.png -O  ebet.png
wget  https://eidoo.io/wp-content/uploads/tokens/veros.png -O  vrs.png
wget  https://eidoo.io/wp-content/uploads/tokens/arbitragect.png -O  arct.png
wget  https://eidoo.io/wp-content/uploads/tokens/iethereum.png -O  ieth.png
wget  https://eidoo.io/wp-content/uploads/tokens/kubera-coin.png -O  kbr.png
wget  https://eidoo.io/wp-content/uploads/tokens/pluscoin.png -O  plc.png
wget  https://eidoo.io/wp-content/uploads/tokens/zcash-gold.png -O  zcg.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethereumcash.png -O  ecash.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitair.png -O  btca.png
wget  https://eidoo.io/wp-content/uploads/tokens/minereum.png -O  mne.png
wget  https://eidoo.io/wp-content/uploads/tokens/ether-for-the-rest-of-the-world.png -O  e4row.png
wget  https://eidoo.io/wp-content/uploads/tokens/newbium.png -O  newb.png
wget  https://eidoo.io/wp-content/uploads/tokens/link-platform.png -O  lnk.png
wget  https://eidoo.io/wp-content/uploads/tokens/trackr.png -O  tkr.png
wget  https://eidoo.io/wp-content/uploads/tokens/senderon.png -O  sdrn.png
wget  https://eidoo.io/wp-content/uploads/tokens/cartaxi-token.png -O  ctx.png
wget  https://eidoo.io/wp-content/uploads/tokens/lendconnect.png -O  lct.png
wget  https://eidoo.io/wp-content/uploads/tokens/crystal-clear.png -O  cct.png
wget  https://eidoo.io/wp-content/uploads/tokens/ccore.png -O  cco.png
wget  https://eidoo.io/wp-content/uploads/tokens/erc20.png -O  erc20.png
wget  https://eidoo.io/wp-content/uploads/tokens/eaglecoin.png -O  eagle.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethereum-gold.png -O  etg.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethgas.png -O  egas.png
wget  https://eidoo.io/wp-content/uploads/tokens/network-token.png -O  ntwk.png
wget  https://eidoo.io/wp-content/uploads/tokens/300-token.png -O  300.png
wget  https://eidoo.io/wp-content/uploads/tokens/fujinto.png -O  nto.png
wget  https://eidoo.io/wp-content/uploads/tokens/enigma.png -O  xng.png
wget  https://eidoo.io/wp-content/uploads/tokens/postoken.png -O  pos.png
wget  https://eidoo.io/wp-content/uploads/tokens/idice.png -O  ice.png
wget  https://eidoo.io/wp-content/uploads/tokens/dalecoin.png -O  dalc.png
wget  https://eidoo.io/wp-content/uploads/tokens/trident.png -O  trdt.png
wget  https://eidoo.io/wp-content/uploads/tokens/corethum.png -O  crtm.png
wget  https://eidoo.io/wp-content/uploads/tokens/guess.png -O  guess.png
wget  https://eidoo.io/wp-content/uploads/tokens/brat.png -O  brat.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitasean.png -O  bas.png
wget  https://eidoo.io/wp-content/uploads/tokens/remicoin.png -O  rmc.png
wget  https://eidoo.io/wp-content/uploads/tokens/exchangen.png -O  exn.png
wget  https://eidoo.io/wp-content/uploads/tokens/bolenum.png -O  bln.png
wget  https://eidoo.io/wp-content/uploads/tokens/neurodao.png -O  ndao.png
wget  https://eidoo.io/wp-content/uploads/tokens/coimatic-3.png -O  ctic3.png
wget  https://eidoo.io/wp-content/uploads/tokens/poly-ai.png -O  ai.png
wget  https://eidoo.io/wp-content/uploads/tokens/futurexe.png -O  fxe.png
wget  https://eidoo.io/wp-content/uploads/tokens/ereal.png -O  ereal.png
wget  https://eidoo.io/wp-content/uploads/tokens/exchange-union.png -O  xuc.png
wget  https://eidoo.io/wp-content/uploads/tokens/comsa-eth.png -O  cms.png
wget  https://eidoo.io/wp-content/uploads/tokens/lltoken.png -O  llt.png
wget  https://eidoo.io/wp-content/uploads/tokens/ug-token.png -O  ugt.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitserial.png -O  bte.png
wget  https://eidoo.io/wp-content/uploads/tokens/sphre-air.png -O  xid.png
wget  https://eidoo.io/wp-content/uploads/tokens/blockcdn.png -O  bcdn.png
wget  https://eidoo.io/wp-content/uploads/tokens/ox-fina.png -O  ox.png
wget  https://eidoo.io/wp-content/uploads/tokens/litecoin-gold.png -O  ltg.png
wget  https://eidoo.io/wp-content/uploads/tokens/btcmoon.png -O  btcm.png
wget  https://eidoo.io/wp-content/uploads/tokens/ethereum-lite.png -O  elite.png
wget  https://eidoo.io/wp-content/uploads/tokens/plexcoin.png -O  plx.png
wget  https://eidoo.io/wp-content/uploads/tokens/macro1.png -O  mcr.png
wget  https://eidoo.io/wp-content/uploads/tokens/sand-coin.png -O  snd.png
wget  https://eidoo.io/wp-content/uploads/tokens/hyper-tv.png -O  hytv.png
wget  https://eidoo.io/wp-content/uploads/tokens/blockchain-index.png -O  blx.png
wget  https://eidoo.io/wp-content/uploads/tokens/iquant.png -O  iqt.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitcoin-silver.png -O  btcs.png
wget  https://eidoo.io/wp-content/uploads/tokens/natcoin.png -O  ntc.png
wget  https://eidoo.io/wp-content/uploads/tokens/ibtc.png -O  ibtc.png
wget  https://eidoo.io/wp-content/uploads/tokens/alphabitcoinfund.png -O  abc.png
wget  https://eidoo.io/wp-content/uploads/tokens/dimoncoin.png -O  fudd.png
wget  https://eidoo.io/wp-content/uploads/tokens/cash-poker-pro.png -O  cash.png
wget  https://eidoo.io/wp-content/uploads/tokens/swapcoin.png -O  swp.png
wget  https://eidoo.io/wp-content/uploads/tokens/ebit.png -O  ebit.png
wget  https://eidoo.io/wp-content/uploads/tokens/wi-coin.png -O  wic.png
wget  https://eidoo.io/wp-content/uploads/tokens/hodl-bucks.png -O  hdlb.png
wget  https://eidoo.io/wp-content/uploads/tokens/bitcoin2x.png -O  btc2x.png
wget  https://eidoo.io/wp-content/uploads/tokens/fapcoin.png -O  fap.png
wget  https://eidoo.io/wp-content/uploads/tokens/facecoin.png -O  fc.png
wget  https://eidoo.io/wp-content/uploads/tokens/egold.png -O  egold.png
wget  https://eidoo.io/wp-content/uploads/tokens/eusd.png -O  eusd.png
wget  https://eidoo.io/wp-content/uploads/tokens/bigone-token.png -O  big.png
wget  https://eidoo.io/wp-content/uploads/tokens/fairgame.png -O  fair.png
wget  https://eidoo.io/wp-content/uploads/tokens/cloud.png -O  cld.png
wget  https://eidoo.io/wp-content/uploads/tokens/etherdelta-token.png -O  edt.png
wget  https://eidoo.io/wp-content/uploads/tokens/qube.png -O  qube.png
wget  https://eidoo.io/wp-content/uploads/tokens/investdigital.png -O  idt.png
wget  https://eidoo.io/wp-content/uploads/tokens/read.png -O  read.png
wget  https://eidoo.io/wp-content/uploads/tokens/maggie.png -O  mag.png
wget  https://eidoo.io/wp-content/uploads/tokens/coinmeet.png -O  mee.png
wget  https://eidoo.io/wp-content/uploads/tokens/pundi-x.png -O  pxs.png
wget  https://eidoo.io/wp-content/uploads/tokens/ipchain.png -O  ipc.png
wget  https://eidoo.io/wp-content/uploads/tokens/valuechain.png -O  vlc.png
wget  https://eidoo.io/wp-content/uploads/tokens/indicoin.png -O  indi.png
wget  https://eidoo.io/wp-content/uploads/tokens/etherecash.png -O  ech.png
wget  https://eidoo.io/wp-content/uploads/tokens/topchain.png -O  topc.png
wget  https://eidoo.io/wp-content/uploads/tokens/realchain.png -O  rct.png
wget  https://eidoo.io/wp-content/uploads/tokens/show.png -O  show.png
wget  https://eidoo.io/wp-content/uploads/tokens/lightchain.png -O  light.png
wget  https://eidoo.io/wp-content/uploads/tokens/unlimitedip.png -O  uip.png
wget  https://eidoo.io/wp-content/uploads/tokens/molecular-future.png -O  mof.png
wget  https://eidoo.io/wp-content/uploads/tokens/candy.png -O  candy.png